version: "3.3"
services:
  serverbrowsing:
    ports:
      - "28910:30693"
    command: /opt/openspy/bin/serverbrowsing
    env_file: .env-local
    image: os-core
  qr:
    ports:
      - "27900:30694"
    command: /opt/openspy/bin/qr
    env_file: .env-local
    image: os-core
  natneg:
    ports:
      - "27901:30695"
    command: /opt/openspy/bin/natneg
    env_file: .env-local
    image: os-core
  GP:
    ports:
      - "29900:30974"
    command: /opt/openspy/bin/GP
    env_file: .env-local
    image: os-core
  SM:
    ports:
      - "29901:30734"
    command: /opt/openspy/bin/SM
    env_file: .env-local
    image: os-core
  cdkey:
    ports:
      - "29910:30835"
    command: /opt/openspy/bin/cdkey
    env_file: .env-local
    image: os-core
  gstats:
    ports:
      - "29920:30836"
    command: /opt/openspy/bin/gstats
    env_file: .env-local
    image: os-core
  peerchat:
    ports:
      - "6667:30771"
    command: /opt/openspy/bin/peerchat
    env_file: .env-local
    image: os-core
  FESL-bf2142:
    ports:
      - "18300:30837"
    command: /opt/openspy/bin/FESL
    env_file: .env-local
    image: os-core
    